import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import time
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
def generate_pdf_report(media_pct, roi_df, insights, filename="Anshulytics_AI_mmm_report.pdf"):

    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
    )
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import inch

    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()
    content = []

    # =========================
    # HEADER (LOGO + TITLE)
    # =========================
    try:
        logo = Image("logo2.png", width=1.2*inch, height=1.2*inch)
        content.append(logo)
    except:
        pass

    content.append(Spacer(1, 10))
    content.append(Paragraph("<b>Anshulytics AI Report</b>", styles["Title"]))
    content.append(Paragraph("Marketing Mix Modeling & Optimization Suite", styles["Normal"]))
    content.append(Spacer(1, 20))

    # =========================
    # CONTRIBUTION TABLE
    # =========================
    content.append(Paragraph("<b>Channel Contribution (%)</b>", styles["Heading2"]))
    content.append(Spacer(1, 10))

    contrib_data = [["Channel", "Contribution (%)"]]

    for ch, val in media_pct.items():
        contrib_data.append([ch, f"{val:.2f}%"])

    table = Table(contrib_data, hAlign='LEFT')
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.black),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    content.append(table)
    content.append(Spacer(1, 20))

    # =========================
    # ROI TABLE
    # =========================
    content.append(Paragraph("<b>ROI Analysis</b>", styles["Heading2"]))
    content.append(Spacer(1, 10))

    roi_data = [["Channel", "ROI"]]

    for ch, val in roi_df.items():
        roi_data.append([ch, f"{val:.2f}"])

    table = Table(roi_data, hAlign='LEFT')
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    content.append(table)
    content.append(Spacer(1, 20))

    # =========================
    # INSIGHTS
    # =========================
    content.append(Paragraph("<b>Key Insights</b>", styles["Heading2"]))
    content.append(Spacer(1, 10))

    if insights:
        for ins in insights:
            content.append(Paragraph(f"• {ins}", styles["Normal"]))
            content.append(Spacer(1, 6))
    else:
        content.append(Paragraph("No insights generated", styles["Normal"]))

    content.append(Spacer(1, 30))

    # =========================
    # FOOTER
    # =========================
    content.append(Paragraph(
        "Generated by Anshulytics AI",
        styles["Italic"]
    ))

    # Build PDF
    doc.build(content)

    with open(filename, "rb") as f:
        return f.read()

# =========================
# SESSION STATE INIT
# =========================
if "df" not in st.session_state:
    st.session_state.df = None

if "model_results" not in st.session_state:
    st.session_state.model_results = None

# =========================
# PAGE CONFIG (UPGRADED)
# =========================
st.set_page_config(
    page_title="Anshulytics AI",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =========================
# PREMIUM CSS
# =========================
st.markdown("""
<style>

/* Global */
body {
    background-color: #0E1117;
    color: #E6EDF3;
}

/* Layout spacing */
.block-container {
    padding-top: 1.5rem;
    padding-bottom: 1rem;
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background-color: #111827;
    border-right: 1px solid #222;
}

/* Cards */
.card {
    background-color: #161B22;
    padding: 20px;
    border-radius: 12px;
    border: 1px solid #222;
    margin-bottom: 15px;
}

/* KPI Cards */
.metric-card {
    background-color: #161B22;
    padding: 15px;
    border-radius: 10px;
    border: 1px solid #222;
    text-align: center;
}

/* Typography */
h1 {
    font-size: 32px;
    font-weight: 700;
    color: #E6EDF3;
}

h2 {
    font-size: 22px;
    color: #9CA3AF;
}

h3 {
    font-size: 18px;
    color: #9CA3AF;
}

/* Buttons */
button[kind="primary"] {
    background-color: #4CAF50 !important;
    border-radius: 8px;
}

/* Tabs */
.stTabs [data-baseweb="tab"] {
    font-size: 16px;
    padding: 10px;
}

/* Tables */
[data-testid="stDataFrame"] {
    border-radius: 10px;
    overflow: hidden;
}

/* Hide Streamlit branding */
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}

</style>
""", unsafe_allow_html=True)

# =========================
# =========================
# LOGIN SCREEN (EMAIL BASED)
# =========================

USERS = st.secrets["users"]

def login_screen():
    st.markdown("""
        <style>
        .login-box {
            background-color: #161B22;
            padding: 40px;
            border-radius: 12px;
            border: 1px solid #222;
            width: 400px;
            margin: auto;
            margin-top: 10vh;
            text-align: center;
        }
        .login-title {
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 10px;
        }
        .login-sub {
            color: #9CA3AF;
            margin-bottom: 25px;
        }
        </style>
    """, unsafe_allow_html=True)

    st.markdown('<div class="login-box">', unsafe_allow_html=True)

    try:
        st.image("logo2.png", width=120)
    except:
        pass

    st.markdown('<div class="login-title">Anshulytics AI</div>', unsafe_allow_html=True)
    st.markdown('<div class="login-sub">Login to continue</div>', unsafe_allow_html=True)

    # ✅ NEW: Email + Password
    email = st.text_input("Email")
    password = st.text_input("Password", type="password")

    if st.button("Login"):
        if email in USERS and USERS[email] == password:
            st.session_state["authenticated"] = True
            st.session_state["user"] = email
            st.rerun()
        else:
            st.error("Invalid email or password")

    st.markdown('</div>', unsafe_allow_html=True)


# =========================
# AUTH CONTROL
# =========================

if "authenticated" not in st.session_state:
    st.session_state["authenticated"] = False

if not st.session_state["authenticated"]:
    login_screen()
    st.stop()
# =========================
# HEADER (SHOW ONLY AFTER LOGIN)
# =========================
col1, col2 = st.columns([1, 6])

with col1:
    try:
        st.image("logo2.png", width=120)
    except:
        pass

with col2:
    st.markdown("<h1>Anshulytics AI</h1>", unsafe_allow_html=True)
    st.markdown("<h3>Marketing Mix Modeling & Optimization Suite</h3>", unsafe_allow_html=True)

st.markdown("---")
st.caption("Trusted by Data-Driven Marketing Teams")
st.sidebar.markdown(f"👤 Logged in as: {st.session_state.get('user','')}")


# =========================
# SIDEBAR NAVIGATION
# =========================
st.sidebar.title("Workspace")

page = st.sidebar.radio(
    "Navigation",
    [
        "📈 EDA",
        "📊 MMM Engine",
        "🎯 Scenario Simulator",
        "💰 Budget Optimizer",
        "📘 Help"
    ]
)

st.sidebar.markdown("---")
st.sidebar.caption("Built by Anshul 🚀")

# =========================
# EDA TAB (FINAL CLEAN VERSION)
# =========================
if page == "📈 EDA":

    st.header("📊 Exploratory Data Analysis")

    file = st.file_uploader("Upload CSV", type=["csv"])
    
    if file:
        st.session_state.df = pd.read_csv(file)

    df = st.session_state.df

    # ✅ FIX: Check if df exists
    if df is not None:

        # =========================
        # DATA PREVIEW
        # =========================
        st.subheader("📄 Data Preview")
        st.dataframe(df.head(), use_container_width=True)

        numeric_cols = df.select_dtypes(include=np.number).columns.tolist()

        col1, col2 = st.columns(2)
        sales_col = col1.selectbox("Select Sales Column", numeric_cols, key="eda_sales")
        spend_cols = col2.multiselect("Select Spend Columns", numeric_cols, key="eda_spend")

        if sales_col and spend_cols:

            # =========================
            # TIME SERIES
            # =========================
            st.subheader("📈 Sales & Spend Over Time")

            ts_df = df[[sales_col] + spend_cols].copy()
            st.line_chart(ts_df)

            # =========================
            # CORRELATION MATRIX
            # =========================
            st.subheader("🔥 Correlation Matrix")

            corr = df[[sales_col] + spend_cols].corr()
            st.dataframe(corr, use_container_width=True)

            # =========================
            # CORRELATION WITH SALES
            # =========================
            st.subheader("📊 Correlation with Sales")

            sales_corr = corr[sales_col].drop(sales_col).sort_values(ascending=False)
            st.bar_chart(sales_corr)

            # =========================
            # VIF (MULTICOLLINEARITY)
            # =========================
            st.subheader("⚠️ VIF (Multicollinearity Check)")

            from statsmodels.stats.outliers_influence import variance_inflation_factor

            X = df[spend_cols].dropna()

            vif_data = pd.DataFrame()
            vif_data["Channel"] = spend_cols
            vif_data["VIF"] = [
                variance_inflation_factor(X.values, i)
                for i in range(len(spend_cols))
            ]

            st.dataframe(vif_data, use_container_width=True)

            st.markdown("""
            **Interpretation:**
            - VIF < 5 → Good  
            - VIF 5–10 → Moderate multicollinearity  
            - VIF > 10 → High multicollinearity (problematic)
            """)

            # =========================
            # AUTO INSIGHTS
            # =========================
            st.subheader("🧠 Auto Insights")

            insights = []

            for ch, val in sales_corr.head(3).items():
                insights.append(f"📈 {ch} strongly correlates with sales ({val:.2f})")

            for ch, val in sales_corr[sales_corr < 0].items():
                insights.append(f"🚨 {ch} negatively correlates with sales ({val:.2f}) — check lag or tracking issues")

            for _, row in vif_data.iterrows():
                if row["VIF"] > 10:
                    insights.append(f"⚠️ {row['Channel']} has high multicollinearity (VIF={row['VIF']:.1f})")
                elif row["VIF"] > 5:
                    insights.append(f"⚠️ {row['Channel']} has moderate multicollinearity (VIF={row['VIF']:.1f})")

            if insights:
                for ins in insights:
                    st.markdown(f"- {ins}")
            else:
                st.info("No strong insights detected")

    else:
        # ✅ FIX: Correct placement
        st.info("👆 Upload a CSV file to begin EDA")
        
# =========================
# FUNCTIONS
# =========================
def adstock_transform(x, decay):
    result = np.zeros(len(x))
    for t in range(len(x)):
        result[t] = x[t] + (decay * result[t-1] if t > 0 else 0)
    return result

def hill_saturation(x, alpha, gamma):
    return (x**alpha) / (x**alpha + gamma**alpha)

# =========================
# INSTRUCTIONS TAB
# =========================
if page == "📘 Help":
    st.header("📘 How to Use This MMM Tool")

    st.markdown("""

### 🔁 Adstock (Decay Rate)
Adstock models the **carryover effect of advertising over time**.

- **Low decay (0.0 – 0.3)** → Immediate impact, fades quickly  
- **Medium decay (0.3 – 0.6)** → Moderate carryover  
- **High decay (0.6 – 0.9)** → Long-lasting impact  

👉 Use higher values for **brand channels (TV, YouTube)**  
👉 Use lower values for **performance channels (Search, Meta Ads)**  

---

### 📈 Alpha (Response Curve Shape)
Alpha controls the **steepness of the response curve**.

- **Low alpha (~0.5 – 1.0)** → Gradual increase in returns  
- **Medium alpha (~1.0 – 2.0)** → Balanced response  
- **High alpha (>2.0)** → Sharp increase after threshold  

👉 Higher alpha means **strong response after a certain spend level**

---

### 📉 Gamma (Saturation Level)
Gamma determines **when diminishing returns begin**.

- **Low gamma** → Saturation happens early  
- **High gamma** → Saturation happens later  

👉 Low gamma = good for **performance channels**  
👉 High gamma = suitable for **brand-building channels**

---

### 🎯 Practical Guidelines

| Channel Type     | Decay | Alpha | Gamma |
|------------------|------|-------|-------|
| TV / Branding    | High | Medium | High |
| Digital Display  | Medium | Medium | Medium |
| Search / Performance | Low | High | Low |

---

### ⚠️ Model Diagnostics

- If **Train R² is much higher than Test R²** → Model is likely **overfitting**
- If **ROI values look unrealistic** → Check:
  - data quality  
  - extreme parameter values  

---

### 💡 What You Can Do With This Tool

- 📊 Measure channel contribution  
- 📈 Understand diminishing returns  
- 💰 Optimize budget allocation  
- 🎯 Run scenario simulations  

---

Built with ❤️ by Anshul
""")

# =========================
# MAIN DASHBOARD
# =========================
if page == "📊 MMM Engine":

    df = st.session_state.df

    if df is None:
        st.info("👆 Upload a dataset in EDA section first")
        st.stop()

    st.markdown("### 📊 Data Preview")
    st.dataframe(df.head(), use_container_width=True)

    numeric_cols = df.select_dtypes(include=np.number).columns.tolist()

    col1, col2 = st.columns(2)
    sales_col = col1.selectbox("Sales Column", numeric_cols)
    spend_cols = col2.multiselect("Spend Columns", numeric_cols)

    # =========================
    # VALIDATION
    # =========================
    if not sales_col or not spend_cols:
        st.warning("⚠️ Please select sales and spend columns")
        st.stop()

    # =========================
    # SIDEBAR
    # =========================
    st.sidebar.header("⚙️ Controls")

    params = {}
    for col in spend_cols:
        st.sidebar.subheader(col)
        params[col] = {
            "decay": st.sidebar.slider(f"{col} Decay", 0.0, 1.0, 0.5, key=col+"d"),
            "alpha": st.sidebar.slider(f"{col} Alpha", 0.1, 3.0, 1.5, key=col+"a"),
            "gamma": st.sidebar.slider(f"{col} Gamma", 1.0, 200.0, 100.0, key=col+"g")
        }

    ridge_alpha = st.sidebar.slider("Ridge Alpha", 0.1, 10.0, 1.0)

    # =========================
    # RUN MODEL
    # =========================
    if st.button("🚀 Run MMM Model"):

        st.markdown("### 🤖 MMM Engine Initializing...")
        try:
            st.video(open("robot.mp4", "rb").read())
        except:
            st.info("Add robot.mp4 for animation")

        status = st.empty()
        progress = st.progress(0)

        steps = [
            "🔧 Applying Adstock...",
            "📉 Applying Saturation...",
            "🧠 Training Model...",
            "📊 Calculating Contributions..."
        ]

        for i, step in enumerate(steps):
            status.markdown(f"<div class='card'>{step}</div>", unsafe_allow_html=True)
            time.sleep(0.8)
            progress.progress((i+1)/len(steps))

        # =========================
        # FEATURE ENGINEERING
        # =========================
        transformed_cols = []

        for col in spend_cols:
            p = params[col]
            ad = adstock_transform(df[col].values, p["decay"])
            fr = hill_saturation(ad, p["alpha"], p["gamma"])
            new_col = col+"_t"
            df[new_col] = fr
            transformed_cols.append(new_col)

        df["trend"] = np.arange(len(df))
        df["sin"] = np.sin(2*np.pi*df.index/12)
        df["cos"] = np.cos(2*np.pi*df.index/12)

        features = transformed_cols + ["trend","sin","cos"]

        X = df[features]
        y = df[sales_col]

        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        X_train, X_test, y_train, y_test = train_test_split(
            X_scaled, y, test_size=0.2, random_state=42
        )

        # =========================
        # MULTI MODEL TRAINING
        # =========================
        from sklearn.linear_model import Ridge, Lasso, ElasticNet
        from sklearn.metrics import mean_absolute_percentage_error

        models = {
            "Ridge": Ridge(alpha=ridge_alpha),
            "Lasso": Lasso(alpha=0.1),
            "ElasticNet": ElasticNet(alpha=0.1, l1_ratio=0.5)
        }

        results = []
        trained_models = {}

        for name, m in models.items():
            m.fit(X_train, y_train)

            train_r2 = m.score(X_train, y_train)
            test_r2 = m.score(X_test, y_test)

            preds = m.predict(X_test)
            mape = mean_absolute_percentage_error(y_test, preds)

            results.append({
                "Model": name,
                "Train R²": round(train_r2, 3),
                "Test R²": round(test_r2, 3),
                "MAPE": round(mape, 3)
            })

            trained_models[name] = m

        results_df = pd.DataFrame(results)

        st.subheader("🧠 Model Comparison")
        st.dataframe(results_df, use_container_width=True)

        best_model_name = results_df.sort_values("MAPE").iloc[0]["Model"]
        model = trained_models[best_model_name]

        st.success(f"✅ Best Model Selected: {best_model_name}")

        train_r2 = results_df.loc[results_df["Model"] == best_model_name, "Train R²"].values[0]
        test_r2 = results_df.loc[results_df["Model"] == best_model_name, "Test R²"].values[0]
        # =========================
        # VALIDATION METRICS (NEW)
        # =========================
        from sklearn.metrics import mean_squared_error
        
        preds = model.predict(X_test)
        
        rmse = np.sqrt(mean_squared_error(y_test, preds))
        mape = mean_absolute_percentage_error(y_test, preds)
        
        st.subheader("📉 Model Validation")
        
        col1, col2 = st.columns(2)
        col1.metric("RMSE", round(rmse,2))
        col2.metric("MAPE", round(mape,3))
        
        st.caption("Model validated using hold-out test data")
        
        # =========================
        # ACTUAL vs PREDICTED
        # =========================
        val_df = pd.DataFrame({
            "Actual": y_test.values,
            "Predicted": preds
        })
        
        st.markdown("### 📊 Actual vs Predicted")
        st.line_chart(val_df.reset_index(drop=True))
        
        # =========================
        # RESIDUAL ANALYSIS
        # =========================
        residuals = y_test.values - preds
        
        res_df = pd.DataFrame({
            "Residuals": residuals
        })
        
        st.markdown("### 📉 Residual Distribution")
        st.bar_chart(res_df)

        # =========================
        # ELITE MMM CONTRIBUTION + ROI (INCREMENTAL)
        # =========================
        
        # Full feature set
        X_full = df[features].copy()
        
        # Predict total sales with all channels
        X_full_scaled = scaler.transform(X_full)
        full_pred = model.predict(X_full_scaled).sum()
        
        channel_contrib = {}
        
        # =========================
        # CHANNEL CONTRIBUTION (REMOVE ONE CHANNEL AT A TIME)
        # =========================
        for i, col in enumerate(spend_cols):
        
            temp_df = X_full.copy()
        
            # Zero out only this channel
            transformed_col = transformed_cols[i]
            temp_df[transformed_col] = 0
        
            temp_scaled = scaler.transform(temp_df)
            temp_pred = model.predict(temp_scaled).sum()
        
            contribution = full_pred - temp_pred
        
            # Avoid negative noise
            channel_contrib[col] = max(contribution, 0)
        
        media_contrib = pd.Series(channel_contrib)
        
        # =========================
        # % CONTRIBUTION
        # =========================
        if media_contrib.sum() != 0:
            media_pct = (media_contrib / media_contrib.sum()) * 100
        else:
            media_pct = media_contrib.copy()
        
        # =========================
        # BASELINE (NO MEDIA)
        # =========================
        X_zero = X_full.copy()
        X_zero[transformed_cols] = 0
        
        X_zero_scaled = scaler.transform(X_zero)
        baseline_pred = model.predict(X_zero_scaled).sum()
        
        total_sales = full_pred
        
        if total_sales != 0:
            baseline_pct = (baseline_pred / total_sales) * 100
        else:
            baseline_pct = 0
        
        promo_pct = 100 - baseline_pct
        
        # =========================
        # ROI (TRUE INCREMENTAL)
        # =========================
        spend_totals = df[spend_cols].sum()
        
        roi = {}
        
        for col in spend_cols:
            spend_value = spend_totals[col]
            contrib_value = media_contrib[col]
        
            if spend_value > 0:
                roi[col] = contrib_value / spend_value
            else:
                roi[col] = 0
        
        roi_df = pd.Series(roi)

        # =========================
        # DASHBOARD OUTPUT
        # =========================
        st.success("✅ MMM Analysis Ready")

        col1, col2, col3, col4 = st.columns(4)
        metrics = [
            ("Train R²", round(train_r2,3)),
            ("Test R²", round(test_r2,3)),
            ("Baseline %", f"{baseline_pct:.1f}%"),
            ("Promo %", f"{promo_pct:.1f}%")
        ]

        for col, (label, value) in zip([col1, col2, col3, col4], metrics):
            with col:
                st.markdown(f"""
                <div class='metric-card'>
                <h3>{label}</h3>
                <h2>{value}</h2>
                </div>
                """, unsafe_allow_html=True)

        c1, c2 = st.columns(2)
        with c1:
            st.markdown("<div class='card'>", unsafe_allow_html=True)
            st.subheader("📊 Contribution")
            st.bar_chart(media_pct)
            st.markdown("</div>", unsafe_allow_html=True)

        with c2:
            st.markdown("<div class='card'>", unsafe_allow_html=True)
            st.subheader("📈 ROI")
            st.bar_chart(roi_df)
            st.markdown("</div>", unsafe_allow_html=True)
        # =========================
        # AUTO INSIGHTS
        # =========================
        st.markdown("### 🧠 Key Insights")
        
        insights = []
        
        # Top channels
        top_channels = media_pct.sort_values(ascending=False).head(3)
        for ch, val in top_channels.items():
            insights.append(f"📈 {ch} is a top driver contributing {val:.1f}% of sales")
        
        # Low ROI channels
        low_roi = roi_df.sort_values().head(2)
        for ch, val in low_roi.items():
            insights.append(f"⚠️ {ch} has low ROI ({val:.2f}) — consider reducing spend")
        
        # High ROI channels
        high_roi = roi_df.sort_values(ascending=False).head(2)
        for ch, val in high_roi.items():
            insights.append(f"💰 {ch} has strong ROI ({val:.2f}) — potential to scale")
        
        # Baseline vs promo
        if baseline_pct > 70:
            insights.append("🏠 Majority of sales are driven by baseline (organic/brand strength)")
        else:
            insights.append("📢 Promotions/media are major drivers of sales")
        
        # Display
        for ins in insights:
            st.markdown(f"- {ins}")
        st.session_state["insights"] = insights
        # =========================
        # BUDGET SUGGESTION
        # =========================
        st.markdown("### 💡 Budget Recommendation")
        
        top_growth = roi_df.sort_values(ascending=False).head(3).index.tolist()
        cut_channels = roi_df.sort_values().head(2).index.tolist()
        
        st.markdown(f"""
        - 🚀 Increase investment in: **{', '.join(top_growth)}**
        - ✂️ Reduce spend in: **{', '.join(cut_channels)}**
        - 🔄 Reallocate budget for better efficiency
        """)

        # =========================
        # STORE RESULTS
        # =========================
        st.session_state.model_results = {
            "model": model,
            "scaler": scaler,
            "features": features,
            "params": params,
            "spend_cols": spend_cols,
            "roi_df": roi_df,
            "media_pct": media_pct
        }

        # =========================
        # EXPORT FULL REPORT
        # =========================
        report_df = pd.DataFrame({
            "Channel": spend_cols,
            "Contribution (%)": media_pct.values,
            "ROI": roi_df.values
        })
        
        # =========================
        # EXPORT REPORTS
        # =========================
        insights = st.session_state.get("insights", [])
        
        # CSV Report
        report_df = pd.DataFrame({
            "Channel": spend_cols,
            "Contribution (%)": media_pct.values,
            "ROI": roi_df.values
        })
        
        st.download_button(
            "📥 Download CSV Report",
            data=report_df.to_csv(index=False),
            file_name="mmm_report.csv"
        )
        
        # PDF Report
        pdf_bytes = generate_pdf_report(media_pct, roi_df, insights)
        
        st.download_button(
            "📄 Download PDF Report",
            data=pdf_bytes,
            file_name="mmm_report.pdf"
        )
# =========================
# SIMULATOR (IMPROVED)
# =========================        
if page == "🎯 Scenario Simulator":

    if st.session_state.model_results is None:
        st.warning("Run model first from Dashboard")
        st.stop()

    data = st.session_state.model_results
    df = st.session_state.df

    model = data["model"]
    scaler = data["scaler"]
    features = data["features"]
    params = data["params"]
    spend_cols = data["spend_cols"]

    st.header("🎯 Scenario Simulator")

    # =========================
    # USER INPUT
    # =========================
    scenario = {}
    for col in spend_cols:
        change = st.slider(f"{col} Spend Change (%)", -50, 100, 0)
        scenario[col] = df[col].mean() * (1 + change/100)

    scenario_df = pd.DataFrame([scenario])

    # =========================
    # TRANSFORM SCENARIO
    # =========================
    for col in spend_cols:
        p = params[col]
        ad = adstock_transform(scenario_df[col].values, p["decay"])
        scenario_df[col] = hill_saturation(ad, p["alpha"], p["gamma"])

    scenario_X = scaler.transform(
        scenario_df.reindex(columns=features, fill_value=0)
    )

    predicted = model.predict(scenario_X)[0]

    # =========================
    # BASELINE CALCULATION (NEW)
    # =========================
    baseline_input = df[spend_cols].mean().to_frame().T

    for col in spend_cols:
        p = params[col]
        ad = adstock_transform(baseline_input[col].values, p["decay"])
        baseline_input[col] = hill_saturation(ad, p["alpha"], p["gamma"])

    baseline_X = scaler.transform(
        baseline_input.reindex(columns=features, fill_value=0)
    )

    baseline_pred = model.predict(baseline_X)[0]

    # =========================
    # OUTPUT (COMPARISON)
    # =========================
    delta = predicted - baseline_pred

    col1, col2 = st.columns(2)
    col1.metric("Baseline Sales", round(baseline_pred, 2))
    col2.metric("New Sales", round(predicted, 2), delta=round(delta, 2))
# =========================
# OPTIMIZER (REAL)
# =========================
if page == "💰 Budget Optimizer":

    if st.session_state.model_results is None:
        st.warning("Run model first from Dashboard")
        st.stop()

    from scipy.optimize import minimize

    data = st.session_state.model_results
    df = st.session_state.df

    model = data["model"]
    scaler = data["scaler"]
    features = data["features"]
    params = data["params"]
    spend_cols = data["spend_cols"]

    st.header("💰 Budget Optimizer")

    total_budget = st.number_input("Total Budget", value=1000000)

    # =========================
    # OBJECTIVE FUNCTION
    # =========================
    def objective(spend_values):

        spend_dict = dict(zip(spend_cols, spend_values))
        temp_df = pd.DataFrame([spend_dict])

        # Apply transformations
        for col in spend_cols:
            p = params[col]
            ad = adstock_transform(temp_df[col].values, p["decay"])
            temp_df[col] = hill_saturation(ad, p["alpha"], p["gamma"])

        X = temp_df.reindex(columns=features, fill_value=0)
        X_scaled = scaler.transform(X)

        pred = model.predict(X_scaled)[0]

        return -pred  # maximize → minimize negative

    # =========================
    # CONSTRAINT
    # =========================
    constraints = ({
        'type': 'eq',
        'fun': lambda x: np.sum(x) - total_budget
    })

    # =========================
    # BOUNDS
    # =========================
    bounds = [(0, total_budget) for _ in spend_cols]

    # =========================
    # INITIAL GUESS
    # =========================
    x0 = np.array([total_budget / len(spend_cols)] * len(spend_cols))

    # =========================
    # OPTIMIZATION
    # =========================
    result = minimize(
        objective,
        x0,
        bounds=bounds,
        constraints=constraints,
        method='SLSQP'
    )

    optimal_spend = result.x

    # =========================
    # FINAL PREDICTION
    # =========================
    final_pred = -result.fun

    # =========================
    # OUTPUT
    # =========================
    opt_df = pd.DataFrame({
        "Channel": spend_cols,
        "Optimal Budget": optimal_spend
    })

    st.success("✅ Optimal Allocation Computed")

    st.metric("📊 Expected Sales", round(final_pred,2))

    st.dataframe(opt_df, use_container_width=True)
    st.bar_chart(opt_df.set_index("Channel"))
